//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPCNETUnitTesting.UPCNETServiceCursoClase {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Services.upcnet.upc.com/", ConfigurationName="UPCNETServiceCursoClase.UPCNETServiceCursoClase")]
    public interface UPCNETServiceCursoClase {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/getCursoClaseAlumnoRequest" +
            "", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/getCursoClaseAlumnoRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseAlumnoResponse getCursoClaseAlumno(UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/getCursoClaseAlumnoRequest" +
            "", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/getCursoClaseAlumnoRespons" +
            "e")]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseAlumnoResponse> getCursoClaseAlumnoAsync(UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseAlumnoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/getCursoClaseByIdCursoRequ" +
            "est", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/getCursoClaseByIdCursoResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIdCursoResponse getCursoClaseByIdCurso(UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIdCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/getCursoClaseByIdCursoRequ" +
            "est", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/getCursoClaseByIdCursoResp" +
            "onse")]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIdCursoResponse> getCursoClaseByIdCursoAsync(UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIdCursoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/getCursoClaseByIDRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/getCursoClaseByIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIDResponse getCursoClaseByID(UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/getCursoClaseByIDRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/getCursoClaseByIDResponse")]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIDResponse> getCursoClaseByIDAsync(UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIDRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/getCursoClaseRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/getCursoClaseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseResponse getCursoClase(UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/getCursoClaseRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/getCursoClaseResponse")]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseResponse> getCursoClaseAsync(UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/setCursoClaseRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/setCursoClaseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UPCNETUnitTesting.UPCNETServiceCursoClase.setCursoClaseResponse setCursoClase(UPCNETUnitTesting.UPCNETServiceCursoClase.setCursoClaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/setCursoClaseRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/setCursoClaseResponse")]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCursoClase.setCursoClaseResponse> setCursoClaseAsync(UPCNETUnitTesting.UPCNETServiceCursoClase.setCursoClaseRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/editCursoClaseRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/editCursoClaseResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UPCNETUnitTesting.UPCNETServiceCursoClase.editCursoClaseResponse editCursoClase(UPCNETUnitTesting.UPCNETServiceCursoClase.editCursoClaseRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/editCursoClaseRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoClase/editCursoClaseResponse")]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCursoClase.editCursoClaseResponse> editCursoClaseAsync(UPCNETUnitTesting.UPCNETServiceCursoClase.editCursoClaseRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services.upcnet.upc.com/")]
    public partial class cursoClaseAlumno : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cursoField;
        
        private string diaField;
        
        private System.DateTime horaFinalField;
        
        private bool horaFinalFieldSpecified;
        
        private System.DateTime horaInicialField;
        
        private bool horaInicialFieldSpecified;
        
        private string idCursoField;
        
        private string profesorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string curso {
            get {
                return this.cursoField;
            }
            set {
                this.cursoField = value;
                this.RaisePropertyChanged("curso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string dia {
            get {
                return this.diaField;
            }
            set {
                this.diaField = value;
                this.RaisePropertyChanged("dia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime horaFinal {
            get {
                return this.horaFinalField;
            }
            set {
                this.horaFinalField = value;
                this.RaisePropertyChanged("horaFinal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool horaFinalSpecified {
            get {
                return this.horaFinalFieldSpecified;
            }
            set {
                this.horaFinalFieldSpecified = value;
                this.RaisePropertyChanged("horaFinalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime horaInicial {
            get {
                return this.horaInicialField;
            }
            set {
                this.horaInicialField = value;
                this.RaisePropertyChanged("horaInicial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool horaInicialSpecified {
            get {
                return this.horaInicialFieldSpecified;
            }
            set {
                this.horaInicialFieldSpecified = value;
                this.RaisePropertyChanged("horaInicialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string idCurso {
            get {
                return this.idCursoField;
            }
            set {
                this.idCursoField = value;
                this.RaisePropertyChanged("idCurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string profesor {
            get {
                return this.profesorField;
            }
            set {
                this.profesorField = value;
                this.RaisePropertyChanged("profesor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services.upcnet.upc.com/")]
    public partial class cursoClase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string diaField;
        
        private System.DateTime horaFinField;
        
        private bool horaFinFieldSpecified;
        
        private System.DateTime horaIniField;
        
        private bool horaIniFieldSpecified;
        
        private string idClaseField;
        
        private string idCursoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dia {
            get {
                return this.diaField;
            }
            set {
                this.diaField = value;
                this.RaisePropertyChanged("dia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime horaFin {
            get {
                return this.horaFinField;
            }
            set {
                this.horaFinField = value;
                this.RaisePropertyChanged("horaFin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool horaFinSpecified {
            get {
                return this.horaFinFieldSpecified;
            }
            set {
                this.horaFinFieldSpecified = value;
                this.RaisePropertyChanged("horaFinSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime horaIni {
            get {
                return this.horaIniField;
            }
            set {
                this.horaIniField = value;
                this.RaisePropertyChanged("horaIni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool horaIniSpecified {
            get {
                return this.horaIniFieldSpecified;
            }
            set {
                this.horaIniFieldSpecified = value;
                this.RaisePropertyChanged("horaIniSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string idClase {
            get {
                return this.idClaseField;
            }
            set {
                this.idClaseField = value;
                this.RaisePropertyChanged("idClase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string idCurso {
            get {
                return this.idCursoField;
            }
            set {
                this.idCursoField = value;
                this.RaisePropertyChanged("idCurso");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoClaseAlumno", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoClaseAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idAlumno;
        
        public getCursoClaseAlumnoRequest() {
        }
        
        public getCursoClaseAlumnoRequest(string idAlumno) {
            this.idAlumno = idAlumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoClaseAlumnoResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoClaseAlumnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETUnitTesting.UPCNETServiceCursoClase.cursoClaseAlumno[] @return;
        
        public getCursoClaseAlumnoResponse() {
        }
        
        public getCursoClaseAlumnoResponse(UPCNETUnitTesting.UPCNETServiceCursoClase.cursoClaseAlumno[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoClaseByIdCurso", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoClaseByIdCursoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getCursoClaseByIdCursoRequest() {
        }
        
        public getCursoClaseByIdCursoRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoClaseByIdCursoResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoClaseByIdCursoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETUnitTesting.UPCNETServiceCursoClase.cursoClase[] @return;
        
        public getCursoClaseByIdCursoResponse() {
        }
        
        public getCursoClaseByIdCursoResponse(UPCNETUnitTesting.UPCNETServiceCursoClase.cursoClase[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoClaseByID", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoClaseByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public getCursoClaseByIDRequest() {
        }
        
        public getCursoClaseByIDRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoClaseByIDResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoClaseByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETUnitTesting.UPCNETServiceCursoClase.cursoClase @return;
        
        public getCursoClaseByIDResponse() {
        }
        
        public getCursoClaseByIDResponse(UPCNETUnitTesting.UPCNETServiceCursoClase.cursoClase @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoClase", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoClaseRequest {
        
        public getCursoClaseRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoClaseResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoClaseResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETUnitTesting.UPCNETServiceCursoClase.cursoClase[] @return;
        
        public getCursoClaseResponse() {
        }
        
        public getCursoClaseResponse(UPCNETUnitTesting.UPCNETServiceCursoClase.cursoClase[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setCursoClase", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class setCursoClaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETUnitTesting.UPCNETServiceCursoClase.cursoClase arg0;
        
        public setCursoClaseRequest() {
        }
        
        public setCursoClaseRequest(UPCNETUnitTesting.UPCNETServiceCursoClase.cursoClase arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setCursoClaseResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class setCursoClaseResponse {
        
        public setCursoClaseResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editCursoClase", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class editCursoClaseRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETUnitTesting.UPCNETServiceCursoClase.cursoClase arg0;
        
        public editCursoClaseRequest() {
        }
        
        public editCursoClaseRequest(UPCNETUnitTesting.UPCNETServiceCursoClase.cursoClase arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editCursoClaseResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class editCursoClaseResponse {
        
        public editCursoClaseResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UPCNETServiceCursoClaseChannel : UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UPCNETServiceCursoClaseClient : System.ServiceModel.ClientBase<UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase>, UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase {
        
        public UPCNETServiceCursoClaseClient() {
        }
        
        public UPCNETServiceCursoClaseClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UPCNETServiceCursoClaseClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPCNETServiceCursoClaseClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPCNETServiceCursoClaseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseAlumnoResponse UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase.getCursoClaseAlumno(UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseAlumnoRequest request) {
            return base.Channel.getCursoClaseAlumno(request);
        }
        
        public UPCNETUnitTesting.UPCNETServiceCursoClase.cursoClaseAlumno[] getCursoClaseAlumno(string idAlumno) {
            UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseAlumnoRequest inValue = new UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseAlumnoRequest();
            inValue.idAlumno = idAlumno;
            UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseAlumnoResponse retVal = ((UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase)(this)).getCursoClaseAlumno(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseAlumnoResponse> UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase.getCursoClaseAlumnoAsync(UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseAlumnoRequest request) {
            return base.Channel.getCursoClaseAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseAlumnoResponse> getCursoClaseAlumnoAsync(string idAlumno) {
            UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseAlumnoRequest inValue = new UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseAlumnoRequest();
            inValue.idAlumno = idAlumno;
            return ((UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase)(this)).getCursoClaseAlumnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIdCursoResponse UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase.getCursoClaseByIdCurso(UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIdCursoRequest request) {
            return base.Channel.getCursoClaseByIdCurso(request);
        }
        
        public UPCNETUnitTesting.UPCNETServiceCursoClase.cursoClase[] getCursoClaseByIdCurso(string arg0) {
            UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIdCursoRequest inValue = new UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIdCursoRequest();
            inValue.arg0 = arg0;
            UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIdCursoResponse retVal = ((UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase)(this)).getCursoClaseByIdCurso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIdCursoResponse> UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase.getCursoClaseByIdCursoAsync(UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIdCursoRequest request) {
            return base.Channel.getCursoClaseByIdCursoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIdCursoResponse> getCursoClaseByIdCursoAsync(string arg0) {
            UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIdCursoRequest inValue = new UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIdCursoRequest();
            inValue.arg0 = arg0;
            return ((UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase)(this)).getCursoClaseByIdCursoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIDResponse UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase.getCursoClaseByID(UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIDRequest request) {
            return base.Channel.getCursoClaseByID(request);
        }
        
        public UPCNETUnitTesting.UPCNETServiceCursoClase.cursoClase getCursoClaseByID(string arg0, string arg1) {
            UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIDRequest inValue = new UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIDRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIDResponse retVal = ((UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase)(this)).getCursoClaseByID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIDResponse> UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase.getCursoClaseByIDAsync(UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIDRequest request) {
            return base.Channel.getCursoClaseByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIDResponse> getCursoClaseByIDAsync(string arg0, string arg1) {
            UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIDRequest inValue = new UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseByIDRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase)(this)).getCursoClaseByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseResponse UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase.getCursoClase(UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseRequest request) {
            return base.Channel.getCursoClase(request);
        }
        
        public UPCNETUnitTesting.UPCNETServiceCursoClase.cursoClase[] getCursoClase() {
            UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseRequest inValue = new UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseRequest();
            UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseResponse retVal = ((UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase)(this)).getCursoClase(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseResponse> UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase.getCursoClaseAsync(UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseRequest request) {
            return base.Channel.getCursoClaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseResponse> getCursoClaseAsync() {
            UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseRequest inValue = new UPCNETUnitTesting.UPCNETServiceCursoClase.getCursoClaseRequest();
            return ((UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase)(this)).getCursoClaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETUnitTesting.UPCNETServiceCursoClase.setCursoClaseResponse UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase.setCursoClase(UPCNETUnitTesting.UPCNETServiceCursoClase.setCursoClaseRequest request) {
            return base.Channel.setCursoClase(request);
        }
        
        public void setCursoClase(UPCNETUnitTesting.UPCNETServiceCursoClase.cursoClase arg0) {
            UPCNETUnitTesting.UPCNETServiceCursoClase.setCursoClaseRequest inValue = new UPCNETUnitTesting.UPCNETServiceCursoClase.setCursoClaseRequest();
            inValue.arg0 = arg0;
            UPCNETUnitTesting.UPCNETServiceCursoClase.setCursoClaseResponse retVal = ((UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase)(this)).setCursoClase(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCursoClase.setCursoClaseResponse> UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase.setCursoClaseAsync(UPCNETUnitTesting.UPCNETServiceCursoClase.setCursoClaseRequest request) {
            return base.Channel.setCursoClaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCursoClase.setCursoClaseResponse> setCursoClaseAsync(UPCNETUnitTesting.UPCNETServiceCursoClase.cursoClase arg0) {
            UPCNETUnitTesting.UPCNETServiceCursoClase.setCursoClaseRequest inValue = new UPCNETUnitTesting.UPCNETServiceCursoClase.setCursoClaseRequest();
            inValue.arg0 = arg0;
            return ((UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase)(this)).setCursoClaseAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETUnitTesting.UPCNETServiceCursoClase.editCursoClaseResponse UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase.editCursoClase(UPCNETUnitTesting.UPCNETServiceCursoClase.editCursoClaseRequest request) {
            return base.Channel.editCursoClase(request);
        }
        
        public void editCursoClase(UPCNETUnitTesting.UPCNETServiceCursoClase.cursoClase arg0) {
            UPCNETUnitTesting.UPCNETServiceCursoClase.editCursoClaseRequest inValue = new UPCNETUnitTesting.UPCNETServiceCursoClase.editCursoClaseRequest();
            inValue.arg0 = arg0;
            UPCNETUnitTesting.UPCNETServiceCursoClase.editCursoClaseResponse retVal = ((UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase)(this)).editCursoClase(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCursoClase.editCursoClaseResponse> UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase.editCursoClaseAsync(UPCNETUnitTesting.UPCNETServiceCursoClase.editCursoClaseRequest request) {
            return base.Channel.editCursoClaseAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCursoClase.editCursoClaseResponse> editCursoClaseAsync(UPCNETUnitTesting.UPCNETServiceCursoClase.cursoClase arg0) {
            UPCNETUnitTesting.UPCNETServiceCursoClase.editCursoClaseRequest inValue = new UPCNETUnitTesting.UPCNETServiceCursoClase.editCursoClaseRequest();
            inValue.arg0 = arg0;
            return ((UPCNETUnitTesting.UPCNETServiceCursoClase.UPCNETServiceCursoClase)(this)).editCursoClaseAsync(inValue);
        }
    }
}
