//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPCNETUnitTesting.UPCNETServiceCategoria {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Services.upcnet.upc.com/", ConfigurationName="UPCNETServiceCategoria.UPCNETServiceCategoria")]
    public interface UPCNETServiceCategoria {
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCategoria/setCategoriaRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCategoria/setCategoriaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UPCNETUnitTesting.UPCNETServiceCategoria.setCategoriaResponse setCategoria(UPCNETUnitTesting.UPCNETServiceCategoria.setCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCategoria/setCategoriaRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCategoria/setCategoriaResponse")]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCategoria.setCategoriaResponse> setCategoriaAsync(UPCNETUnitTesting.UPCNETServiceCategoria.setCategoriaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCategoria/getCategoriaRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCategoria/getCategoriaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETUnitTesting.UPCNETServiceCategoria.getCategoriaResponse getCategoria(UPCNETUnitTesting.UPCNETServiceCategoria.getCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCategoria/getCategoriaRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCategoria/getCategoriaResponse")]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCategoria.getCategoriaResponse> getCategoriaAsync(UPCNETUnitTesting.UPCNETServiceCategoria.getCategoriaRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCategoria/editCategoriaRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCategoria/editCategoriaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UPCNETUnitTesting.UPCNETServiceCategoria.editCategoriaResponse editCategoria(UPCNETUnitTesting.UPCNETServiceCategoria.editCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCategoria/editCategoriaRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCategoria/editCategoriaResponse")]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCategoria.editCategoriaResponse> editCategoriaAsync(UPCNETUnitTesting.UPCNETServiceCategoria.editCategoriaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setCategoria", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class setCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public setCategoriaRequest() {
        }
        
        public setCategoriaRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setCategoriaResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class setCategoriaResponse {
        
        public setCategoriaResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services.upcnet.upc.com/")]
    public partial class categoria : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idCategoriaField;
        
        private float montoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                this.idCategoriaField = value;
                this.RaisePropertyChanged("idCategoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public float monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
                this.RaisePropertyChanged("monto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCategoria", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCategoriaRequest {
        
        public getCategoriaRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCategoriaResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETUnitTesting.UPCNETServiceCategoria.categoria[] @return;
        
        public getCategoriaResponse() {
        }
        
        public getCategoriaResponse(UPCNETUnitTesting.UPCNETServiceCategoria.categoria[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editCategoria", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class editCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public editCategoriaRequest() {
        }
        
        public editCategoriaRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editCategoriaResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class editCategoriaResponse {
        
        public editCategoriaResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UPCNETServiceCategoriaChannel : UPCNETUnitTesting.UPCNETServiceCategoria.UPCNETServiceCategoria, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UPCNETServiceCategoriaClient : System.ServiceModel.ClientBase<UPCNETUnitTesting.UPCNETServiceCategoria.UPCNETServiceCategoria>, UPCNETUnitTesting.UPCNETServiceCategoria.UPCNETServiceCategoria {
        
        public UPCNETServiceCategoriaClient() {
        }
        
        public UPCNETServiceCategoriaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UPCNETServiceCategoriaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPCNETServiceCategoriaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPCNETServiceCategoriaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETUnitTesting.UPCNETServiceCategoria.setCategoriaResponse UPCNETUnitTesting.UPCNETServiceCategoria.UPCNETServiceCategoria.setCategoria(UPCNETUnitTesting.UPCNETServiceCategoria.setCategoriaRequest request) {
            return base.Channel.setCategoria(request);
        }
        
        public void setCategoria(string arg0, string arg1) {
            UPCNETUnitTesting.UPCNETServiceCategoria.setCategoriaRequest inValue = new UPCNETUnitTesting.UPCNETServiceCategoria.setCategoriaRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            UPCNETUnitTesting.UPCNETServiceCategoria.setCategoriaResponse retVal = ((UPCNETUnitTesting.UPCNETServiceCategoria.UPCNETServiceCategoria)(this)).setCategoria(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCategoria.setCategoriaResponse> UPCNETUnitTesting.UPCNETServiceCategoria.UPCNETServiceCategoria.setCategoriaAsync(UPCNETUnitTesting.UPCNETServiceCategoria.setCategoriaRequest request) {
            return base.Channel.setCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCategoria.setCategoriaResponse> setCategoriaAsync(string arg0, string arg1) {
            UPCNETUnitTesting.UPCNETServiceCategoria.setCategoriaRequest inValue = new UPCNETUnitTesting.UPCNETServiceCategoria.setCategoriaRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((UPCNETUnitTesting.UPCNETServiceCategoria.UPCNETServiceCategoria)(this)).setCategoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETUnitTesting.UPCNETServiceCategoria.getCategoriaResponse UPCNETUnitTesting.UPCNETServiceCategoria.UPCNETServiceCategoria.getCategoria(UPCNETUnitTesting.UPCNETServiceCategoria.getCategoriaRequest request) {
            return base.Channel.getCategoria(request);
        }
        
        public UPCNETUnitTesting.UPCNETServiceCategoria.categoria[] getCategoria() {
            UPCNETUnitTesting.UPCNETServiceCategoria.getCategoriaRequest inValue = new UPCNETUnitTesting.UPCNETServiceCategoria.getCategoriaRequest();
            UPCNETUnitTesting.UPCNETServiceCategoria.getCategoriaResponse retVal = ((UPCNETUnitTesting.UPCNETServiceCategoria.UPCNETServiceCategoria)(this)).getCategoria(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCategoria.getCategoriaResponse> UPCNETUnitTesting.UPCNETServiceCategoria.UPCNETServiceCategoria.getCategoriaAsync(UPCNETUnitTesting.UPCNETServiceCategoria.getCategoriaRequest request) {
            return base.Channel.getCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCategoria.getCategoriaResponse> getCategoriaAsync() {
            UPCNETUnitTesting.UPCNETServiceCategoria.getCategoriaRequest inValue = new UPCNETUnitTesting.UPCNETServiceCategoria.getCategoriaRequest();
            return ((UPCNETUnitTesting.UPCNETServiceCategoria.UPCNETServiceCategoria)(this)).getCategoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETUnitTesting.UPCNETServiceCategoria.editCategoriaResponse UPCNETUnitTesting.UPCNETServiceCategoria.UPCNETServiceCategoria.editCategoria(UPCNETUnitTesting.UPCNETServiceCategoria.editCategoriaRequest request) {
            return base.Channel.editCategoria(request);
        }
        
        public void editCategoria(string arg0, string arg1) {
            UPCNETUnitTesting.UPCNETServiceCategoria.editCategoriaRequest inValue = new UPCNETUnitTesting.UPCNETServiceCategoria.editCategoriaRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            UPCNETUnitTesting.UPCNETServiceCategoria.editCategoriaResponse retVal = ((UPCNETUnitTesting.UPCNETServiceCategoria.UPCNETServiceCategoria)(this)).editCategoria(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCategoria.editCategoriaResponse> UPCNETUnitTesting.UPCNETServiceCategoria.UPCNETServiceCategoria.editCategoriaAsync(UPCNETUnitTesting.UPCNETServiceCategoria.editCategoriaRequest request) {
            return base.Channel.editCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCategoria.editCategoriaResponse> editCategoriaAsync(string arg0, string arg1) {
            UPCNETUnitTesting.UPCNETServiceCategoria.editCategoriaRequest inValue = new UPCNETUnitTesting.UPCNETServiceCategoria.editCategoriaRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((UPCNETUnitTesting.UPCNETServiceCategoria.UPCNETServiceCategoria)(this)).editCategoriaAsync(inValue);
        }
    }
}
