//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPCNETSystemCliente.UPCNETServiceCurso {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Services.upcnet.upc.com/", ConfigurationName="UPCNETServiceCurso.UPCNETServiceCurso")]
    public interface UPCNETServiceCurso {
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCurso/editCursoRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCurso/editCursoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UPCNETSystemCliente.UPCNETServiceCurso.editCursoResponse editCurso(UPCNETSystemCliente.UPCNETServiceCurso.editCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCurso/editCursoRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCurso/editCursoResponse")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCurso.editCursoResponse> editCursoAsync(UPCNETSystemCliente.UPCNETServiceCurso.editCursoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCurso/getCursoByIdRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCurso/getCursoByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETSystemCliente.UPCNETServiceCurso.getCursoByIdResponse getCursoById(UPCNETSystemCliente.UPCNETServiceCurso.getCursoByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCurso/getCursoByIdRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCurso/getCursoByIdResponse")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCurso.getCursoByIdResponse> getCursoByIdAsync(UPCNETSystemCliente.UPCNETServiceCurso.getCursoByIdRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCurso/setCursoRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCurso/setCursoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UPCNETSystemCliente.UPCNETServiceCurso.setCursoResponse setCurso(UPCNETSystemCliente.UPCNETServiceCurso.setCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCurso/setCursoRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCurso/setCursoResponse")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCurso.setCursoResponse> setCursoAsync(UPCNETSystemCliente.UPCNETServiceCurso.setCursoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCurso/getCursosRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCurso/getCursosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETSystemCliente.UPCNETServiceCurso.getCursosResponse getCursos(UPCNETSystemCliente.UPCNETServiceCurso.getCursosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCurso/getCursosRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCurso/getCursosResponse")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCurso.getCursosResponse> getCursosAsync(UPCNETSystemCliente.UPCNETServiceCurso.getCursosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services.upcnet.upc.com/")]
    public partial class curso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cicloDeCursoField;
        
        private string idCursoField;
        
        private string idProfesorField;
        
        private int maxInasistenciaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cicloDeCurso {
            get {
                return this.cicloDeCursoField;
            }
            set {
                this.cicloDeCursoField = value;
                this.RaisePropertyChanged("cicloDeCurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string idCurso {
            get {
                return this.idCursoField;
            }
            set {
                this.idCursoField = value;
                this.RaisePropertyChanged("idCurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string idProfesor {
            get {
                return this.idProfesorField;
            }
            set {
                this.idProfesorField = value;
                this.RaisePropertyChanged("idProfesor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int maxInasistencia {
            get {
                return this.maxInasistenciaField;
            }
            set {
                this.maxInasistenciaField = value;
                this.RaisePropertyChanged("maxInasistencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editCurso", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class editCursoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceCurso.curso arg0;
        
        public editCursoRequest() {
        }
        
        public editCursoRequest(UPCNETSystemCliente.UPCNETServiceCurso.curso arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editCursoResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class editCursoResponse {
        
        public editCursoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoById", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getCursoByIdRequest() {
        }
        
        public getCursoByIdRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoByIdResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceCurso.curso @return;
        
        public getCursoByIdResponse() {
        }
        
        public getCursoByIdResponse(UPCNETSystemCliente.UPCNETServiceCurso.curso @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setCurso", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class setCursoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceCurso.curso arg0;
        
        public setCursoRequest() {
        }
        
        public setCursoRequest(UPCNETSystemCliente.UPCNETServiceCurso.curso arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setCursoResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class setCursoResponse {
        
        public setCursoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursos", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursosRequest {
        
        public getCursosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursosResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceCurso.curso[] @return;
        
        public getCursosResponse() {
        }
        
        public getCursosResponse(UPCNETSystemCliente.UPCNETServiceCurso.curso[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UPCNETServiceCursoChannel : UPCNETSystemCliente.UPCNETServiceCurso.UPCNETServiceCurso, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UPCNETServiceCursoClient : System.ServiceModel.ClientBase<UPCNETSystemCliente.UPCNETServiceCurso.UPCNETServiceCurso>, UPCNETSystemCliente.UPCNETServiceCurso.UPCNETServiceCurso {
        
        public UPCNETServiceCursoClient() {
        }
        
        public UPCNETServiceCursoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UPCNETServiceCursoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPCNETServiceCursoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPCNETServiceCursoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceCurso.editCursoResponse UPCNETSystemCliente.UPCNETServiceCurso.UPCNETServiceCurso.editCurso(UPCNETSystemCliente.UPCNETServiceCurso.editCursoRequest request) {
            return base.Channel.editCurso(request);
        }
        
        public void editCurso(UPCNETSystemCliente.UPCNETServiceCurso.curso arg0) {
            UPCNETSystemCliente.UPCNETServiceCurso.editCursoRequest inValue = new UPCNETSystemCliente.UPCNETServiceCurso.editCursoRequest();
            inValue.arg0 = arg0;
            UPCNETSystemCliente.UPCNETServiceCurso.editCursoResponse retVal = ((UPCNETSystemCliente.UPCNETServiceCurso.UPCNETServiceCurso)(this)).editCurso(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCurso.editCursoResponse> UPCNETSystemCliente.UPCNETServiceCurso.UPCNETServiceCurso.editCursoAsync(UPCNETSystemCliente.UPCNETServiceCurso.editCursoRequest request) {
            return base.Channel.editCursoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCurso.editCursoResponse> editCursoAsync(UPCNETSystemCliente.UPCNETServiceCurso.curso arg0) {
            UPCNETSystemCliente.UPCNETServiceCurso.editCursoRequest inValue = new UPCNETSystemCliente.UPCNETServiceCurso.editCursoRequest();
            inValue.arg0 = arg0;
            return ((UPCNETSystemCliente.UPCNETServiceCurso.UPCNETServiceCurso)(this)).editCursoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceCurso.getCursoByIdResponse UPCNETSystemCliente.UPCNETServiceCurso.UPCNETServiceCurso.getCursoById(UPCNETSystemCliente.UPCNETServiceCurso.getCursoByIdRequest request) {
            return base.Channel.getCursoById(request);
        }
        
        public UPCNETSystemCliente.UPCNETServiceCurso.curso getCursoById(string arg0) {
            UPCNETSystemCliente.UPCNETServiceCurso.getCursoByIdRequest inValue = new UPCNETSystemCliente.UPCNETServiceCurso.getCursoByIdRequest();
            inValue.arg0 = arg0;
            UPCNETSystemCliente.UPCNETServiceCurso.getCursoByIdResponse retVal = ((UPCNETSystemCliente.UPCNETServiceCurso.UPCNETServiceCurso)(this)).getCursoById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCurso.getCursoByIdResponse> UPCNETSystemCliente.UPCNETServiceCurso.UPCNETServiceCurso.getCursoByIdAsync(UPCNETSystemCliente.UPCNETServiceCurso.getCursoByIdRequest request) {
            return base.Channel.getCursoByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCurso.getCursoByIdResponse> getCursoByIdAsync(string arg0) {
            UPCNETSystemCliente.UPCNETServiceCurso.getCursoByIdRequest inValue = new UPCNETSystemCliente.UPCNETServiceCurso.getCursoByIdRequest();
            inValue.arg0 = arg0;
            return ((UPCNETSystemCliente.UPCNETServiceCurso.UPCNETServiceCurso)(this)).getCursoByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceCurso.setCursoResponse UPCNETSystemCliente.UPCNETServiceCurso.UPCNETServiceCurso.setCurso(UPCNETSystemCliente.UPCNETServiceCurso.setCursoRequest request) {
            return base.Channel.setCurso(request);
        }
        
        public void setCurso(UPCNETSystemCliente.UPCNETServiceCurso.curso arg0) {
            UPCNETSystemCliente.UPCNETServiceCurso.setCursoRequest inValue = new UPCNETSystemCliente.UPCNETServiceCurso.setCursoRequest();
            inValue.arg0 = arg0;
            UPCNETSystemCliente.UPCNETServiceCurso.setCursoResponse retVal = ((UPCNETSystemCliente.UPCNETServiceCurso.UPCNETServiceCurso)(this)).setCurso(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCurso.setCursoResponse> UPCNETSystemCliente.UPCNETServiceCurso.UPCNETServiceCurso.setCursoAsync(UPCNETSystemCliente.UPCNETServiceCurso.setCursoRequest request) {
            return base.Channel.setCursoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCurso.setCursoResponse> setCursoAsync(UPCNETSystemCliente.UPCNETServiceCurso.curso arg0) {
            UPCNETSystemCliente.UPCNETServiceCurso.setCursoRequest inValue = new UPCNETSystemCliente.UPCNETServiceCurso.setCursoRequest();
            inValue.arg0 = arg0;
            return ((UPCNETSystemCliente.UPCNETServiceCurso.UPCNETServiceCurso)(this)).setCursoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceCurso.getCursosResponse UPCNETSystemCliente.UPCNETServiceCurso.UPCNETServiceCurso.getCursos(UPCNETSystemCliente.UPCNETServiceCurso.getCursosRequest request) {
            return base.Channel.getCursos(request);
        }
        
        public UPCNETSystemCliente.UPCNETServiceCurso.curso[] getCursos() {
            UPCNETSystemCliente.UPCNETServiceCurso.getCursosRequest inValue = new UPCNETSystemCliente.UPCNETServiceCurso.getCursosRequest();
            UPCNETSystemCliente.UPCNETServiceCurso.getCursosResponse retVal = ((UPCNETSystemCliente.UPCNETServiceCurso.UPCNETServiceCurso)(this)).getCursos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCurso.getCursosResponse> UPCNETSystemCliente.UPCNETServiceCurso.UPCNETServiceCurso.getCursosAsync(UPCNETSystemCliente.UPCNETServiceCurso.getCursosRequest request) {
            return base.Channel.getCursosAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCurso.getCursosResponse> getCursosAsync() {
            UPCNETSystemCliente.UPCNETServiceCurso.getCursosRequest inValue = new UPCNETSystemCliente.UPCNETServiceCurso.getCursosRequest();
            return ((UPCNETSystemCliente.UPCNETServiceCurso.UPCNETServiceCurso)(this)).getCursosAsync(inValue);
        }
    }
}
