//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPCNETUnitTesting.UPCNETServiceRecurso {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Services.upcnet.upc.com/", ConfigurationName="UPCNETServiceRecurso.UPCNETServiceRecurso")]
    public interface UPCNETServiceRecurso {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceRecurso/getRecursoRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceRecurso/getRecursoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETUnitTesting.UPCNETServiceRecurso.getRecursoResponse getRecurso(UPCNETUnitTesting.UPCNETServiceRecurso.getRecursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceRecurso/getRecursoRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceRecurso/getRecursoResponse")]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceRecurso.getRecursoResponse> getRecursoAsync(UPCNETUnitTesting.UPCNETServiceRecurso.getRecursoRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceRecurso/setRecursoRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceRecurso/setRecursoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UPCNETUnitTesting.UPCNETServiceRecurso.setRecursoResponse setRecurso(UPCNETUnitTesting.UPCNETServiceRecurso.setRecursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceRecurso/setRecursoRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceRecurso/setRecursoResponse")]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceRecurso.setRecursoResponse> setRecursoAsync(UPCNETUnitTesting.UPCNETServiceRecurso.setRecursoRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceRecurso/editRecursoRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceRecurso/editRecursoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UPCNETUnitTesting.UPCNETServiceRecurso.editRecursoResponse editRecurso(UPCNETUnitTesting.UPCNETServiceRecurso.editRecursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceRecurso/editRecursoRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceRecurso/editRecursoResponse")]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceRecurso.editRecursoResponse> editRecursoAsync(UPCNETUnitTesting.UPCNETServiceRecurso.editRecursoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services.upcnet.upc.com/")]
    public partial class recurso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadHorasField;
        
        private date fechaPedidoField;
        
        private string iDAlumnoField;
        
        private string iDProfesorField;
        
        private string iDRecursoField;
        
        private string nombreRecursoField;
        
        private bool reservadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidadHoras {
            get {
                return this.cantidadHorasField;
            }
            set {
                this.cantidadHorasField = value;
                this.RaisePropertyChanged("cantidadHoras");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public date fechaPedido {
            get {
                return this.fechaPedidoField;
            }
            set {
                this.fechaPedidoField = value;
                this.RaisePropertyChanged("fechaPedido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IDAlumno {
            get {
                return this.iDAlumnoField;
            }
            set {
                this.iDAlumnoField = value;
                this.RaisePropertyChanged("IDAlumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IDProfesor {
            get {
                return this.iDProfesorField;
            }
            set {
                this.iDProfesorField = value;
                this.RaisePropertyChanged("IDProfesor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string IDRecurso {
            get {
                return this.iDRecursoField;
            }
            set {
                this.iDRecursoField = value;
                this.RaisePropertyChanged("IDRecurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombreRecurso {
            get {
                return this.nombreRecursoField;
            }
            set {
                this.nombreRecursoField = value;
                this.RaisePropertyChanged("nombreRecurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public bool reservado {
            get {
                return this.reservadoField;
            }
            set {
                this.reservadoField = value;
                this.RaisePropertyChanged("reservado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services.upcnet.upc.com/")]
    public partial class date : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRecurso", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getRecursoRequest {
        
        public getRecursoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRecursoResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getRecursoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETUnitTesting.UPCNETServiceRecurso.recurso[] @return;
        
        public getRecursoResponse() {
        }
        
        public getRecursoResponse(UPCNETUnitTesting.UPCNETServiceRecurso.recurso[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setRecurso", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class setRecursoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETUnitTesting.UPCNETServiceRecurso.recurso arg0;
        
        public setRecursoRequest() {
        }
        
        public setRecursoRequest(UPCNETUnitTesting.UPCNETServiceRecurso.recurso arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setRecursoResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class setRecursoResponse {
        
        public setRecursoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editRecurso", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class editRecursoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETUnitTesting.UPCNETServiceRecurso.recurso arg0;
        
        public editRecursoRequest() {
        }
        
        public editRecursoRequest(UPCNETUnitTesting.UPCNETServiceRecurso.recurso arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editRecursoResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class editRecursoResponse {
        
        public editRecursoResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UPCNETServiceRecursoChannel : UPCNETUnitTesting.UPCNETServiceRecurso.UPCNETServiceRecurso, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UPCNETServiceRecursoClient : System.ServiceModel.ClientBase<UPCNETUnitTesting.UPCNETServiceRecurso.UPCNETServiceRecurso>, UPCNETUnitTesting.UPCNETServiceRecurso.UPCNETServiceRecurso {
        
        public UPCNETServiceRecursoClient() {
        }
        
        public UPCNETServiceRecursoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UPCNETServiceRecursoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPCNETServiceRecursoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPCNETServiceRecursoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETUnitTesting.UPCNETServiceRecurso.getRecursoResponse UPCNETUnitTesting.UPCNETServiceRecurso.UPCNETServiceRecurso.getRecurso(UPCNETUnitTesting.UPCNETServiceRecurso.getRecursoRequest request) {
            return base.Channel.getRecurso(request);
        }
        
        public UPCNETUnitTesting.UPCNETServiceRecurso.recurso[] getRecurso() {
            UPCNETUnitTesting.UPCNETServiceRecurso.getRecursoRequest inValue = new UPCNETUnitTesting.UPCNETServiceRecurso.getRecursoRequest();
            UPCNETUnitTesting.UPCNETServiceRecurso.getRecursoResponse retVal = ((UPCNETUnitTesting.UPCNETServiceRecurso.UPCNETServiceRecurso)(this)).getRecurso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceRecurso.getRecursoResponse> UPCNETUnitTesting.UPCNETServiceRecurso.UPCNETServiceRecurso.getRecursoAsync(UPCNETUnitTesting.UPCNETServiceRecurso.getRecursoRequest request) {
            return base.Channel.getRecursoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceRecurso.getRecursoResponse> getRecursoAsync() {
            UPCNETUnitTesting.UPCNETServiceRecurso.getRecursoRequest inValue = new UPCNETUnitTesting.UPCNETServiceRecurso.getRecursoRequest();
            return ((UPCNETUnitTesting.UPCNETServiceRecurso.UPCNETServiceRecurso)(this)).getRecursoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETUnitTesting.UPCNETServiceRecurso.setRecursoResponse UPCNETUnitTesting.UPCNETServiceRecurso.UPCNETServiceRecurso.setRecurso(UPCNETUnitTesting.UPCNETServiceRecurso.setRecursoRequest request) {
            return base.Channel.setRecurso(request);
        }
        
        public void setRecurso(UPCNETUnitTesting.UPCNETServiceRecurso.recurso arg0) {
            UPCNETUnitTesting.UPCNETServiceRecurso.setRecursoRequest inValue = new UPCNETUnitTesting.UPCNETServiceRecurso.setRecursoRequest();
            inValue.arg0 = arg0;
            UPCNETUnitTesting.UPCNETServiceRecurso.setRecursoResponse retVal = ((UPCNETUnitTesting.UPCNETServiceRecurso.UPCNETServiceRecurso)(this)).setRecurso(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceRecurso.setRecursoResponse> UPCNETUnitTesting.UPCNETServiceRecurso.UPCNETServiceRecurso.setRecursoAsync(UPCNETUnitTesting.UPCNETServiceRecurso.setRecursoRequest request) {
            return base.Channel.setRecursoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceRecurso.setRecursoResponse> setRecursoAsync(UPCNETUnitTesting.UPCNETServiceRecurso.recurso arg0) {
            UPCNETUnitTesting.UPCNETServiceRecurso.setRecursoRequest inValue = new UPCNETUnitTesting.UPCNETServiceRecurso.setRecursoRequest();
            inValue.arg0 = arg0;
            return ((UPCNETUnitTesting.UPCNETServiceRecurso.UPCNETServiceRecurso)(this)).setRecursoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETUnitTesting.UPCNETServiceRecurso.editRecursoResponse UPCNETUnitTesting.UPCNETServiceRecurso.UPCNETServiceRecurso.editRecurso(UPCNETUnitTesting.UPCNETServiceRecurso.editRecursoRequest request) {
            return base.Channel.editRecurso(request);
        }
        
        public void editRecurso(UPCNETUnitTesting.UPCNETServiceRecurso.recurso arg0) {
            UPCNETUnitTesting.UPCNETServiceRecurso.editRecursoRequest inValue = new UPCNETUnitTesting.UPCNETServiceRecurso.editRecursoRequest();
            inValue.arg0 = arg0;
            UPCNETUnitTesting.UPCNETServiceRecurso.editRecursoResponse retVal = ((UPCNETUnitTesting.UPCNETServiceRecurso.UPCNETServiceRecurso)(this)).editRecurso(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceRecurso.editRecursoResponse> UPCNETUnitTesting.UPCNETServiceRecurso.UPCNETServiceRecurso.editRecursoAsync(UPCNETUnitTesting.UPCNETServiceRecurso.editRecursoRequest request) {
            return base.Channel.editRecursoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceRecurso.editRecursoResponse> editRecursoAsync(UPCNETUnitTesting.UPCNETServiceRecurso.recurso arg0) {
            UPCNETUnitTesting.UPCNETServiceRecurso.editRecursoRequest inValue = new UPCNETUnitTesting.UPCNETServiceRecurso.editRecursoRequest();
            inValue.arg0 = arg0;
            return ((UPCNETUnitTesting.UPCNETServiceRecurso.UPCNETServiceRecurso)(this)).editRecursoAsync(inValue);
        }
    }
}
