//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPCNETUnitTesting.UPCNETServiceCiclo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Services.upcnet.upc.com/", ConfigurationName="UPCNETServiceCiclo.UPCNETServiceCiclo")]
    public interface UPCNETServiceCiclo {
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCiclo/editCicloRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCiclo/editCicloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UPCNETUnitTesting.UPCNETServiceCiclo.editCicloResponse editCiclo(UPCNETUnitTesting.UPCNETServiceCiclo.editCicloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCiclo/editCicloRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCiclo/editCicloResponse")]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCiclo.editCicloResponse> editCicloAsync(UPCNETUnitTesting.UPCNETServiceCiclo.editCicloRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCiclo/getCicloRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCiclo/getCicloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETUnitTesting.UPCNETServiceCiclo.getCicloResponse getCiclo(UPCNETUnitTesting.UPCNETServiceCiclo.getCicloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCiclo/getCicloRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCiclo/getCicloResponse")]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCiclo.getCicloResponse> getCicloAsync(UPCNETUnitTesting.UPCNETServiceCiclo.getCicloRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCiclo/setCicloRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCiclo/setCicloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UPCNETUnitTesting.UPCNETServiceCiclo.setCicloResponse setCiclo(UPCNETUnitTesting.UPCNETServiceCiclo.setCicloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCiclo/setCicloRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCiclo/setCicloResponse")]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCiclo.setCicloResponse> setCicloAsync(UPCNETUnitTesting.UPCNETServiceCiclo.setCicloRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services.upcnet.upc.com/")]
    public partial class ciclo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool boleta1Field;
        
        private bool boleta2Field;
        
        private bool boleta3Field;
        
        private string iDAlumnoField;
        
        private string iDCicloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool boleta1 {
            get {
                return this.boleta1Field;
            }
            set {
                this.boleta1Field = value;
                this.RaisePropertyChanged("boleta1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool boleta2 {
            get {
                return this.boleta2Field;
            }
            set {
                this.boleta2Field = value;
                this.RaisePropertyChanged("boleta2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool boleta3 {
            get {
                return this.boleta3Field;
            }
            set {
                this.boleta3Field = value;
                this.RaisePropertyChanged("boleta3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IDAlumno {
            get {
                return this.iDAlumnoField;
            }
            set {
                this.iDAlumnoField = value;
                this.RaisePropertyChanged("IDAlumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string IDCiclo {
            get {
                return this.iDCicloField;
            }
            set {
                this.iDCicloField = value;
                this.RaisePropertyChanged("IDCiclo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editCiclo", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class editCicloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETUnitTesting.UPCNETServiceCiclo.ciclo arg0;
        
        public editCicloRequest() {
        }
        
        public editCicloRequest(UPCNETUnitTesting.UPCNETServiceCiclo.ciclo arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editCicloResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class editCicloResponse {
        
        public editCicloResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCiclo", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCicloRequest {
        
        public getCicloRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCicloResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCicloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETUnitTesting.UPCNETServiceCiclo.ciclo[] @return;
        
        public getCicloResponse() {
        }
        
        public getCicloResponse(UPCNETUnitTesting.UPCNETServiceCiclo.ciclo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setCiclo", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class setCicloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETUnitTesting.UPCNETServiceCiclo.ciclo arg0;
        
        public setCicloRequest() {
        }
        
        public setCicloRequest(UPCNETUnitTesting.UPCNETServiceCiclo.ciclo arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setCicloResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class setCicloResponse {
        
        public setCicloResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UPCNETServiceCicloChannel : UPCNETUnitTesting.UPCNETServiceCiclo.UPCNETServiceCiclo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UPCNETServiceCicloClient : System.ServiceModel.ClientBase<UPCNETUnitTesting.UPCNETServiceCiclo.UPCNETServiceCiclo>, UPCNETUnitTesting.UPCNETServiceCiclo.UPCNETServiceCiclo {
        
        public UPCNETServiceCicloClient() {
        }
        
        public UPCNETServiceCicloClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UPCNETServiceCicloClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPCNETServiceCicloClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPCNETServiceCicloClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETUnitTesting.UPCNETServiceCiclo.editCicloResponse UPCNETUnitTesting.UPCNETServiceCiclo.UPCNETServiceCiclo.editCiclo(UPCNETUnitTesting.UPCNETServiceCiclo.editCicloRequest request) {
            return base.Channel.editCiclo(request);
        }
        
        public void editCiclo(UPCNETUnitTesting.UPCNETServiceCiclo.ciclo arg0) {
            UPCNETUnitTesting.UPCNETServiceCiclo.editCicloRequest inValue = new UPCNETUnitTesting.UPCNETServiceCiclo.editCicloRequest();
            inValue.arg0 = arg0;
            UPCNETUnitTesting.UPCNETServiceCiclo.editCicloResponse retVal = ((UPCNETUnitTesting.UPCNETServiceCiclo.UPCNETServiceCiclo)(this)).editCiclo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCiclo.editCicloResponse> UPCNETUnitTesting.UPCNETServiceCiclo.UPCNETServiceCiclo.editCicloAsync(UPCNETUnitTesting.UPCNETServiceCiclo.editCicloRequest request) {
            return base.Channel.editCicloAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCiclo.editCicloResponse> editCicloAsync(UPCNETUnitTesting.UPCNETServiceCiclo.ciclo arg0) {
            UPCNETUnitTesting.UPCNETServiceCiclo.editCicloRequest inValue = new UPCNETUnitTesting.UPCNETServiceCiclo.editCicloRequest();
            inValue.arg0 = arg0;
            return ((UPCNETUnitTesting.UPCNETServiceCiclo.UPCNETServiceCiclo)(this)).editCicloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETUnitTesting.UPCNETServiceCiclo.getCicloResponse UPCNETUnitTesting.UPCNETServiceCiclo.UPCNETServiceCiclo.getCiclo(UPCNETUnitTesting.UPCNETServiceCiclo.getCicloRequest request) {
            return base.Channel.getCiclo(request);
        }
        
        public UPCNETUnitTesting.UPCNETServiceCiclo.ciclo[] getCiclo() {
            UPCNETUnitTesting.UPCNETServiceCiclo.getCicloRequest inValue = new UPCNETUnitTesting.UPCNETServiceCiclo.getCicloRequest();
            UPCNETUnitTesting.UPCNETServiceCiclo.getCicloResponse retVal = ((UPCNETUnitTesting.UPCNETServiceCiclo.UPCNETServiceCiclo)(this)).getCiclo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCiclo.getCicloResponse> UPCNETUnitTesting.UPCNETServiceCiclo.UPCNETServiceCiclo.getCicloAsync(UPCNETUnitTesting.UPCNETServiceCiclo.getCicloRequest request) {
            return base.Channel.getCicloAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCiclo.getCicloResponse> getCicloAsync() {
            UPCNETUnitTesting.UPCNETServiceCiclo.getCicloRequest inValue = new UPCNETUnitTesting.UPCNETServiceCiclo.getCicloRequest();
            return ((UPCNETUnitTesting.UPCNETServiceCiclo.UPCNETServiceCiclo)(this)).getCicloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETUnitTesting.UPCNETServiceCiclo.setCicloResponse UPCNETUnitTesting.UPCNETServiceCiclo.UPCNETServiceCiclo.setCiclo(UPCNETUnitTesting.UPCNETServiceCiclo.setCicloRequest request) {
            return base.Channel.setCiclo(request);
        }
        
        public void setCiclo(UPCNETUnitTesting.UPCNETServiceCiclo.ciclo arg0) {
            UPCNETUnitTesting.UPCNETServiceCiclo.setCicloRequest inValue = new UPCNETUnitTesting.UPCNETServiceCiclo.setCicloRequest();
            inValue.arg0 = arg0;
            UPCNETUnitTesting.UPCNETServiceCiclo.setCicloResponse retVal = ((UPCNETUnitTesting.UPCNETServiceCiclo.UPCNETServiceCiclo)(this)).setCiclo(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCiclo.setCicloResponse> UPCNETUnitTesting.UPCNETServiceCiclo.UPCNETServiceCiclo.setCicloAsync(UPCNETUnitTesting.UPCNETServiceCiclo.setCicloRequest request) {
            return base.Channel.setCicloAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETUnitTesting.UPCNETServiceCiclo.setCicloResponse> setCicloAsync(UPCNETUnitTesting.UPCNETServiceCiclo.ciclo arg0) {
            UPCNETUnitTesting.UPCNETServiceCiclo.setCicloRequest inValue = new UPCNETUnitTesting.UPCNETServiceCiclo.setCicloRequest();
            inValue.arg0 = arg0;
            return ((UPCNETUnitTesting.UPCNETServiceCiclo.UPCNETServiceCiclo)(this)).setCicloAsync(inValue);
        }
    }
}
