//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPCNETSystemCliente.UPCNETServiceProfesor {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Services.upcnet.upc.com/", ConfigurationName="UPCNETServiceProfesor.UPCNETServiceProfesor")]
    public interface UPCNETServiceProfesor {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceProfesor/validarLoginRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceProfesor/validarLoginResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETSystemCliente.UPCNETServiceProfesor.validarLoginResponse validarLogin(UPCNETSystemCliente.UPCNETServiceProfesor.validarLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceProfesor/validarLoginRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceProfesor/validarLoginResponse")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.validarLoginResponse> validarLoginAsync(UPCNETSystemCliente.UPCNETServiceProfesor.validarLoginRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceProfesor/getAlumnosEnCursoRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceProfesor/getAlumnosEnCursoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETSystemCliente.UPCNETServiceProfesor.getAlumnosEnCursoResponse getAlumnosEnCurso(UPCNETSystemCliente.UPCNETServiceProfesor.getAlumnosEnCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceProfesor/getAlumnosEnCursoRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceProfesor/getAlumnosEnCursoResponse")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.getAlumnosEnCursoResponse> getAlumnosEnCursoAsync(UPCNETSystemCliente.UPCNETServiceProfesor.getAlumnosEnCursoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceProfesor/getHorarioProfesorRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceProfesor/getHorarioProfesorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETSystemCliente.UPCNETServiceProfesor.getHorarioProfesorResponse getHorarioProfesor(UPCNETSystemCliente.UPCNETServiceProfesor.getHorarioProfesorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceProfesor/getHorarioProfesorRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceProfesor/getHorarioProfesorResponse")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.getHorarioProfesorResponse> getHorarioProfesorAsync(UPCNETSystemCliente.UPCNETServiceProfesor.getHorarioProfesorRequest request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceProfesor/setNotaAlumnosEnCursoRequest" +
            "", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceProfesor/setNotaAlumnosEnCursoRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UPCNETSystemCliente.UPCNETServiceProfesor.setNotaAlumnosEnCursoResponse setNotaAlumnosEnCurso(UPCNETSystemCliente.UPCNETServiceProfesor.setNotaAlumnosEnCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceProfesor/setNotaAlumnosEnCursoRequest" +
            "", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceProfesor/setNotaAlumnosEnCursoRespons" +
            "e")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.setNotaAlumnosEnCursoResponse> setNotaAlumnosEnCursoAsync(UPCNETSystemCliente.UPCNETServiceProfesor.setNotaAlumnosEnCursoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceProfesor/getProfesorByIdRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceProfesor/getProfesorByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorByIdResponse getProfesorById(UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceProfesor/getProfesorByIdRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceProfesor/getProfesorByIdResponse")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorByIdResponse> getProfesorByIdAsync(UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorByIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceProfesor/getCursoProfesorRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceProfesor/getCursoProfesorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETSystemCliente.UPCNETServiceProfesor.getCursoProfesorResponse getCursoProfesor(UPCNETSystemCliente.UPCNETServiceProfesor.getCursoProfesorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceProfesor/getCursoProfesorRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceProfesor/getCursoProfesorResponse")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.getCursoProfesorResponse> getCursoProfesorAsync(UPCNETSystemCliente.UPCNETServiceProfesor.getCursoProfesorRequest request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceProfesor/editProfesorRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceProfesor/editProfesorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UPCNETSystemCliente.UPCNETServiceProfesor.editProfesorResponse editProfesor(UPCNETSystemCliente.UPCNETServiceProfesor.editProfesorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceProfesor/editProfesorRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceProfesor/editProfesorResponse")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.editProfesorResponse> editProfesorAsync(UPCNETSystemCliente.UPCNETServiceProfesor.editProfesorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceProfesor/getProfesorRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceProfesor/getProfesorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorResponse getProfesor(UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceProfesor/getProfesorRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceProfesor/getProfesorResponse")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorResponse> getProfesorAsync(UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorRequest request);
        
        // CODEGEN: El parámetro 'arg0' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceProfesor/setProfesorRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceProfesor/setProfesorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UPCNETSystemCliente.UPCNETServiceProfesor.setProfesorResponse setProfesor(UPCNETSystemCliente.UPCNETServiceProfesor.setProfesorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceProfesor/setProfesorRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceProfesor/setProfesorResponse")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.setProfesorResponse> setProfesorAsync(UPCNETSystemCliente.UPCNETServiceProfesor.setProfesorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarLogin", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class validarLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public validarLoginRequest() {
        }
        
        public validarLoginRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validarLoginResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class validarLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public validarLoginResponse() {
        }
        
        public validarLoginResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services.upcnet.upc.com/")]
    public partial class alumnosEnCurso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoField;
        
        private double efField;
        
        private double epField;
        
        private string iDAlumnoField;
        
        private string iDCursoField;
        
        private string nombreaField;
        
        private string nombrecField;
        
        private double pc1Field;
        
        private double pc2Field;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("apellido");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double ef {
            get {
                return this.efField;
            }
            set {
                this.efField = value;
                this.RaisePropertyChanged("ef");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double ep {
            get {
                return this.epField;
            }
            set {
                this.epField = value;
                this.RaisePropertyChanged("ep");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IDAlumno {
            get {
                return this.iDAlumnoField;
            }
            set {
                this.iDAlumnoField = value;
                this.RaisePropertyChanged("IDAlumno");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string IDCurso {
            get {
                return this.iDCursoField;
            }
            set {
                this.iDCursoField = value;
                this.RaisePropertyChanged("IDCurso");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombrea {
            get {
                return this.nombreaField;
            }
            set {
                this.nombreaField = value;
                this.RaisePropertyChanged("nombrea");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombrec {
            get {
                return this.nombrecField;
            }
            set {
                this.nombrecField = value;
                this.RaisePropertyChanged("nombrec");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double pc1 {
            get {
                return this.pc1Field;
            }
            set {
                this.pc1Field = value;
                this.RaisePropertyChanged("pc1");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double pc2 {
            get {
                return this.pc2Field;
            }
            set {
                this.pc2Field = value;
                this.RaisePropertyChanged("pc2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services.upcnet.upc.com/")]
    public partial class cursoProfesor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cicloDeCursoField;
        
        private string iDCursoField;
        
        private string nombreField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cicloDeCurso {
            get {
                return this.cicloDeCursoField;
            }
            set {
                this.cicloDeCursoField = value;
                this.RaisePropertyChanged("cicloDeCurso");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IDCurso {
            get {
                return this.iDCursoField;
            }
            set {
                this.iDCursoField = value;
                this.RaisePropertyChanged("IDCurso");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services.upcnet.upc.com/")]
    public partial class profesor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoField;
        
        private string correoField;
        
        private string direccionField;
        
        private int dniField;
        
        private bool dniFieldSpecified;
        
        private int edadField;
        
        private bool edadFieldSpecified;
        
        private string idProfesorField;
        
        private string nombreField;
        
        private string passField;
        
        private double sueldoField;
        
        private bool sueldoFieldSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("apellido");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dniSpecified {
            get {
                return this.dniFieldSpecified;
            }
            set {
                this.dniFieldSpecified = value;
                this.RaisePropertyChanged("dniSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int edad {
            get {
                return this.edadField;
            }
            set {
                this.edadField = value;
                this.RaisePropertyChanged("edad");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool edadSpecified {
            get {
                return this.edadFieldSpecified;
            }
            set {
                this.edadFieldSpecified = value;
                this.RaisePropertyChanged("edadSpecified");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string idProfesor {
            get {
                return this.idProfesorField;
            }
            set {
                this.idProfesorField = value;
                this.RaisePropertyChanged("idProfesor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string pass {
            get {
                return this.passField;
            }
            set {
                this.passField = value;
                this.RaisePropertyChanged("pass");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double sueldo {
            get {
                return this.sueldoField;
            }
            set {
                this.sueldoField = value;
                this.RaisePropertyChanged("sueldo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sueldoSpecified {
            get {
                return this.sueldoFieldSpecified;
            }
            set {
                this.sueldoFieldSpecified = value;
                this.RaisePropertyChanged("sueldoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services.upcnet.upc.com/")]
    public partial class horarioProfesor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string diaField;
        
        private string horaFinField;
        
        private string horaIniField;
        
        private string iDCursoField;
        
        private string nombreField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string dia {
            get {
                return this.diaField;
            }
            set {
                this.diaField = value;
                this.RaisePropertyChanged("dia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string horaFin {
            get {
                return this.horaFinField;
            }
            set {
                this.horaFinField = value;
                this.RaisePropertyChanged("horaFin");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string horaIni {
            get {
                return this.horaIniField;
            }
            set {
                this.horaIniField = value;
                this.RaisePropertyChanged("horaIni");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IDCurso {
            get {
                return this.iDCursoField;
            }
            set {
                this.iDCursoField = value;
                this.RaisePropertyChanged("IDCurso");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAlumnosEnCurso", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getAlumnosEnCursoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getAlumnosEnCursoRequest() {
        }
        
        public getAlumnosEnCursoRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAlumnosEnCursoResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getAlumnosEnCursoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceProfesor.alumnosEnCurso[] @return;
        
        public getAlumnosEnCursoResponse() {
        }
        
        public getAlumnosEnCursoResponse(UPCNETSystemCliente.UPCNETServiceProfesor.alumnosEnCurso[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHorarioProfesor", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getHorarioProfesorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getHorarioProfesorRequest() {
        }
        
        public getHorarioProfesorRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getHorarioProfesorResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getHorarioProfesorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceProfesor.horarioProfesor[] @return;
        
        public getHorarioProfesorResponse() {
        }
        
        public getHorarioProfesorResponse(UPCNETSystemCliente.UPCNETServiceProfesor.horarioProfesor[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setNotaAlumnosEnCurso", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class setNotaAlumnosEnCursoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceProfesor.alumnosEnCurso arg0;
        
        public setNotaAlumnosEnCursoRequest() {
        }
        
        public setNotaAlumnosEnCursoRequest(UPCNETSystemCliente.UPCNETServiceProfesor.alumnosEnCurso arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setNotaAlumnosEnCursoResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class setNotaAlumnosEnCursoResponse {
        
        public setNotaAlumnosEnCursoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProfesorById", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getProfesorByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getProfesorByIdRequest() {
        }
        
        public getProfesorByIdRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProfesorByIdResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getProfesorByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceProfesor.profesor @return;
        
        public getProfesorByIdResponse() {
        }
        
        public getProfesorByIdResponse(UPCNETSystemCliente.UPCNETServiceProfesor.profesor @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoProfesor", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoProfesorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getCursoProfesorRequest() {
        }
        
        public getCursoProfesorRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoProfesorResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoProfesorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceProfesor.cursoProfesor[] @return;
        
        public getCursoProfesorResponse() {
        }
        
        public getCursoProfesorResponse(UPCNETSystemCliente.UPCNETServiceProfesor.cursoProfesor[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editProfesor", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class editProfesorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceProfesor.profesor arg0;
        
        public editProfesorRequest() {
        }
        
        public editProfesorRequest(UPCNETSystemCliente.UPCNETServiceProfesor.profesor arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editProfesorResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class editProfesorResponse {
        
        public editProfesorResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProfesor", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getProfesorRequest {
        
        public getProfesorRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProfesorResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getProfesorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceProfesor.profesor[] @return;
        
        public getProfesorResponse() {
        }
        
        public getProfesorResponse(UPCNETSystemCliente.UPCNETServiceProfesor.profesor[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setProfesor", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class setProfesorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceProfesor.profesor arg0;
        
        public setProfesorRequest() {
        }
        
        public setProfesorRequest(UPCNETSystemCliente.UPCNETServiceProfesor.profesor arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setProfesorResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class setProfesorResponse {
        
        public setProfesorResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UPCNETServiceProfesorChannel : UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UPCNETServiceProfesorClient : System.ServiceModel.ClientBase<UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor>, UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor {
        
        public UPCNETServiceProfesorClient() {
        }
        
        public UPCNETServiceProfesorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UPCNETServiceProfesorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPCNETServiceProfesorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPCNETServiceProfesorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceProfesor.validarLoginResponse UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor.validarLogin(UPCNETSystemCliente.UPCNETServiceProfesor.validarLoginRequest request) {
            return base.Channel.validarLogin(request);
        }
        
        public bool validarLogin(string arg0, string arg1) {
            UPCNETSystemCliente.UPCNETServiceProfesor.validarLoginRequest inValue = new UPCNETSystemCliente.UPCNETServiceProfesor.validarLoginRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            UPCNETSystemCliente.UPCNETServiceProfesor.validarLoginResponse retVal = ((UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor)(this)).validarLogin(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.validarLoginResponse> UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor.validarLoginAsync(UPCNETSystemCliente.UPCNETServiceProfesor.validarLoginRequest request) {
            return base.Channel.validarLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.validarLoginResponse> validarLoginAsync(string arg0, string arg1) {
            UPCNETSystemCliente.UPCNETServiceProfesor.validarLoginRequest inValue = new UPCNETSystemCliente.UPCNETServiceProfesor.validarLoginRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor)(this)).validarLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceProfesor.getAlumnosEnCursoResponse UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor.getAlumnosEnCurso(UPCNETSystemCliente.UPCNETServiceProfesor.getAlumnosEnCursoRequest request) {
            return base.Channel.getAlumnosEnCurso(request);
        }
        
        public UPCNETSystemCliente.UPCNETServiceProfesor.alumnosEnCurso[] getAlumnosEnCurso(string arg0) {
            UPCNETSystemCliente.UPCNETServiceProfesor.getAlumnosEnCursoRequest inValue = new UPCNETSystemCliente.UPCNETServiceProfesor.getAlumnosEnCursoRequest();
            inValue.arg0 = arg0;
            UPCNETSystemCliente.UPCNETServiceProfesor.getAlumnosEnCursoResponse retVal = ((UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor)(this)).getAlumnosEnCurso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.getAlumnosEnCursoResponse> UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor.getAlumnosEnCursoAsync(UPCNETSystemCliente.UPCNETServiceProfesor.getAlumnosEnCursoRequest request) {
            return base.Channel.getAlumnosEnCursoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.getAlumnosEnCursoResponse> getAlumnosEnCursoAsync(string arg0) {
            UPCNETSystemCliente.UPCNETServiceProfesor.getAlumnosEnCursoRequest inValue = new UPCNETSystemCliente.UPCNETServiceProfesor.getAlumnosEnCursoRequest();
            inValue.arg0 = arg0;
            return ((UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor)(this)).getAlumnosEnCursoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceProfesor.getHorarioProfesorResponse UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor.getHorarioProfesor(UPCNETSystemCliente.UPCNETServiceProfesor.getHorarioProfesorRequest request) {
            return base.Channel.getHorarioProfesor(request);
        }
        
        public UPCNETSystemCliente.UPCNETServiceProfesor.horarioProfesor[] getHorarioProfesor(string arg0) {
            UPCNETSystemCliente.UPCNETServiceProfesor.getHorarioProfesorRequest inValue = new UPCNETSystemCliente.UPCNETServiceProfesor.getHorarioProfesorRequest();
            inValue.arg0 = arg0;
            UPCNETSystemCliente.UPCNETServiceProfesor.getHorarioProfesorResponse retVal = ((UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor)(this)).getHorarioProfesor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.getHorarioProfesorResponse> UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor.getHorarioProfesorAsync(UPCNETSystemCliente.UPCNETServiceProfesor.getHorarioProfesorRequest request) {
            return base.Channel.getHorarioProfesorAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.getHorarioProfesorResponse> getHorarioProfesorAsync(string arg0) {
            UPCNETSystemCliente.UPCNETServiceProfesor.getHorarioProfesorRequest inValue = new UPCNETSystemCliente.UPCNETServiceProfesor.getHorarioProfesorRequest();
            inValue.arg0 = arg0;
            return ((UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor)(this)).getHorarioProfesorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceProfesor.setNotaAlumnosEnCursoResponse UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor.setNotaAlumnosEnCurso(UPCNETSystemCliente.UPCNETServiceProfesor.setNotaAlumnosEnCursoRequest request) {
            return base.Channel.setNotaAlumnosEnCurso(request);
        }
        
        public void setNotaAlumnosEnCurso(UPCNETSystemCliente.UPCNETServiceProfesor.alumnosEnCurso arg0) {
            UPCNETSystemCliente.UPCNETServiceProfesor.setNotaAlumnosEnCursoRequest inValue = new UPCNETSystemCliente.UPCNETServiceProfesor.setNotaAlumnosEnCursoRequest();
            inValue.arg0 = arg0;
            UPCNETSystemCliente.UPCNETServiceProfesor.setNotaAlumnosEnCursoResponse retVal = ((UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor)(this)).setNotaAlumnosEnCurso(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.setNotaAlumnosEnCursoResponse> UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor.setNotaAlumnosEnCursoAsync(UPCNETSystemCliente.UPCNETServiceProfesor.setNotaAlumnosEnCursoRequest request) {
            return base.Channel.setNotaAlumnosEnCursoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.setNotaAlumnosEnCursoResponse> setNotaAlumnosEnCursoAsync(UPCNETSystemCliente.UPCNETServiceProfesor.alumnosEnCurso arg0) {
            UPCNETSystemCliente.UPCNETServiceProfesor.setNotaAlumnosEnCursoRequest inValue = new UPCNETSystemCliente.UPCNETServiceProfesor.setNotaAlumnosEnCursoRequest();
            inValue.arg0 = arg0;
            return ((UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor)(this)).setNotaAlumnosEnCursoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorByIdResponse UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor.getProfesorById(UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorByIdRequest request) {
            return base.Channel.getProfesorById(request);
        }
        
        public UPCNETSystemCliente.UPCNETServiceProfesor.profesor getProfesorById(string arg0) {
            UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorByIdRequest inValue = new UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorByIdRequest();
            inValue.arg0 = arg0;
            UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorByIdResponse retVal = ((UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor)(this)).getProfesorById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorByIdResponse> UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor.getProfesorByIdAsync(UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorByIdRequest request) {
            return base.Channel.getProfesorByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorByIdResponse> getProfesorByIdAsync(string arg0) {
            UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorByIdRequest inValue = new UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorByIdRequest();
            inValue.arg0 = arg0;
            return ((UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor)(this)).getProfesorByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceProfesor.getCursoProfesorResponse UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor.getCursoProfesor(UPCNETSystemCliente.UPCNETServiceProfesor.getCursoProfesorRequest request) {
            return base.Channel.getCursoProfesor(request);
        }
        
        public UPCNETSystemCliente.UPCNETServiceProfesor.cursoProfesor[] getCursoProfesor(string arg0) {
            UPCNETSystemCliente.UPCNETServiceProfesor.getCursoProfesorRequest inValue = new UPCNETSystemCliente.UPCNETServiceProfesor.getCursoProfesorRequest();
            inValue.arg0 = arg0;
            UPCNETSystemCliente.UPCNETServiceProfesor.getCursoProfesorResponse retVal = ((UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor)(this)).getCursoProfesor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.getCursoProfesorResponse> UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor.getCursoProfesorAsync(UPCNETSystemCliente.UPCNETServiceProfesor.getCursoProfesorRequest request) {
            return base.Channel.getCursoProfesorAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.getCursoProfesorResponse> getCursoProfesorAsync(string arg0) {
            UPCNETSystemCliente.UPCNETServiceProfesor.getCursoProfesorRequest inValue = new UPCNETSystemCliente.UPCNETServiceProfesor.getCursoProfesorRequest();
            inValue.arg0 = arg0;
            return ((UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor)(this)).getCursoProfesorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceProfesor.editProfesorResponse UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor.editProfesor(UPCNETSystemCliente.UPCNETServiceProfesor.editProfesorRequest request) {
            return base.Channel.editProfesor(request);
        }
        
        public void editProfesor(UPCNETSystemCliente.UPCNETServiceProfesor.profesor arg0) {
            UPCNETSystemCliente.UPCNETServiceProfesor.editProfesorRequest inValue = new UPCNETSystemCliente.UPCNETServiceProfesor.editProfesorRequest();
            inValue.arg0 = arg0;
            UPCNETSystemCliente.UPCNETServiceProfesor.editProfesorResponse retVal = ((UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor)(this)).editProfesor(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.editProfesorResponse> UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor.editProfesorAsync(UPCNETSystemCliente.UPCNETServiceProfesor.editProfesorRequest request) {
            return base.Channel.editProfesorAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.editProfesorResponse> editProfesorAsync(UPCNETSystemCliente.UPCNETServiceProfesor.profesor arg0) {
            UPCNETSystemCliente.UPCNETServiceProfesor.editProfesorRequest inValue = new UPCNETSystemCliente.UPCNETServiceProfesor.editProfesorRequest();
            inValue.arg0 = arg0;
            return ((UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor)(this)).editProfesorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorResponse UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor.getProfesor(UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorRequest request) {
            return base.Channel.getProfesor(request);
        }
        
        public UPCNETSystemCliente.UPCNETServiceProfesor.profesor[] getProfesor() {
            UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorRequest inValue = new UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorRequest();
            UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorResponse retVal = ((UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor)(this)).getProfesor(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorResponse> UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor.getProfesorAsync(UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorRequest request) {
            return base.Channel.getProfesorAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorResponse> getProfesorAsync() {
            UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorRequest inValue = new UPCNETSystemCliente.UPCNETServiceProfesor.getProfesorRequest();
            return ((UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor)(this)).getProfesorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceProfesor.setProfesorResponse UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor.setProfesor(UPCNETSystemCliente.UPCNETServiceProfesor.setProfesorRequest request) {
            return base.Channel.setProfesor(request);
        }
        
        public void setProfesor(UPCNETSystemCliente.UPCNETServiceProfesor.profesor arg0) {
            UPCNETSystemCliente.UPCNETServiceProfesor.setProfesorRequest inValue = new UPCNETSystemCliente.UPCNETServiceProfesor.setProfesorRequest();
            inValue.arg0 = arg0;
            UPCNETSystemCliente.UPCNETServiceProfesor.setProfesorResponse retVal = ((UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor)(this)).setProfesor(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.setProfesorResponse> UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor.setProfesorAsync(UPCNETSystemCliente.UPCNETServiceProfesor.setProfesorRequest request) {
            return base.Channel.setProfesorAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceProfesor.setProfesorResponse> setProfesorAsync(UPCNETSystemCliente.UPCNETServiceProfesor.profesor arg0) {
            UPCNETSystemCliente.UPCNETServiceProfesor.setProfesorRequest inValue = new UPCNETSystemCliente.UPCNETServiceProfesor.setProfesorRequest();
            inValue.arg0 = arg0;
            return ((UPCNETSystemCliente.UPCNETServiceProfesor.UPCNETServiceProfesor)(this)).setProfesorAsync(inValue);
        }
    }
}
