//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPCNETSystemCliente.UPCNETServiceCursoAlumno {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Services.upcnet.upc.com/", ConfigurationName="UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno")]
    public interface UPCNETServiceCursoAlumno {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnoByIDRequest" +
            "", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnoByIDRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIDResponse getCursoAlumnoByID(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnoByIDRequest" +
            "", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnoByIDRespons" +
            "e")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIDResponse> getCursoAlumnoByIDAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIDRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnoByIdCursoRe" +
            "quest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnoByIdCursoRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdCursoResponse getCursoAlumnoByIdCurso(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnoByIdCursoRe" +
            "quest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnoByIdCursoRe" +
            "sponse")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdCursoResponse> getCursoAlumnoByIdCursoAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdCursoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoByIdAlumnoRequest" +
            "", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoByIdAlumnoRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoByIdAlumnoResponse getCursoByIdAlumno(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoByIdAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoByIdAlumnoRequest" +
            "", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoByIdAlumnoRespons" +
            "e")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoByIdAlumnoResponse> getCursoByIdAlumnoAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoByIdAlumnoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnoReporteRequ" +
            "est", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnoReporteResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoReporteResponse getCursoAlumnoReporte(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoReporteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnoReporteRequ" +
            "est", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnoReporteResp" +
            "onse")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoReporteResponse> getCursoAlumnoReporteAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoReporteRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/editCursoAlumnoRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/editCursoAlumnoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.editCursoAlumnoResponse editCursoAlumno(UPCNETSystemCliente.UPCNETServiceCursoAlumno.editCursoAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/editCursoAlumnoRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/editCursoAlumnoResponse")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.editCursoAlumnoResponse> editCursoAlumnoAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.editCursoAlumnoRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnoRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoResponse getCursoAlumno(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnoRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/getCursoAlumnoResponse")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoResponse> getCursoAlumnoAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoRequest request);
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/setCursoAlumnoRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/setCursoAlumnoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoResponse setCursoAlumno(UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/setCursoAlumnoRequest", ReplyAction="http://Services.upcnet.upc.com/UPCNETServiceCursoAlumno/setCursoAlumnoResponse")]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoResponse> setCursoAlumnoAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services.upcnet.upc.com/")]
    public partial class cursoAlumno : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool delegadoField;
        
        private double efField;
        
        private double epField;
        
        private string idAlumnoField;
        
        private string idCursoField;
        
        private int inasistenciasField;
        
        private double pc1Field;
        
        private double pc2Field;
        
        private bool retiradoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool delegado {
            get {
                return this.delegadoField;
            }
            set {
                this.delegadoField = value;
                this.RaisePropertyChanged("delegado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double ef {
            get {
                return this.efField;
            }
            set {
                this.efField = value;
                this.RaisePropertyChanged("ef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double ep {
            get {
                return this.epField;
            }
            set {
                this.epField = value;
                this.RaisePropertyChanged("ep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string idAlumno {
            get {
                return this.idAlumnoField;
            }
            set {
                this.idAlumnoField = value;
                this.RaisePropertyChanged("idAlumno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string idCurso {
            get {
                return this.idCursoField;
            }
            set {
                this.idCursoField = value;
                this.RaisePropertyChanged("idCurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int inasistencias {
            get {
                return this.inasistenciasField;
            }
            set {
                this.inasistenciasField = value;
                this.RaisePropertyChanged("inasistencias");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double pc1 {
            get {
                return this.pc1Field;
            }
            set {
                this.pc1Field = value;
                this.RaisePropertyChanged("pc1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public double pc2 {
            get {
                return this.pc2Field;
            }
            set {
                this.pc2Field = value;
                this.RaisePropertyChanged("pc2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public bool retirado {
            get {
                return this.retiradoField;
            }
            set {
                this.retiradoField = value;
                this.RaisePropertyChanged("retirado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services.upcnet.upc.com/")]
    public partial class cursoAlumnoReporte : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cursoField;
        
        private double efField;
        
        private double epField;
        
        private string idCursoField;
        
        private double pc1Field;
        
        private double pc2Field;
        
        private string profesorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string curso {
            get {
                return this.cursoField;
            }
            set {
                this.cursoField = value;
                this.RaisePropertyChanged("curso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double ef {
            get {
                return this.efField;
            }
            set {
                this.efField = value;
                this.RaisePropertyChanged("ef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double ep {
            get {
                return this.epField;
            }
            set {
                this.epField = value;
                this.RaisePropertyChanged("ep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string idCurso {
            get {
                return this.idCursoField;
            }
            set {
                this.idCursoField = value;
                this.RaisePropertyChanged("idCurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public double pc1 {
            get {
                return this.pc1Field;
            }
            set {
                this.pc1Field = value;
                this.RaisePropertyChanged("pc1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public double pc2 {
            get {
                return this.pc2Field;
            }
            set {
                this.pc2Field = value;
                this.RaisePropertyChanged("pc2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string profesor {
            get {
                return this.profesorField;
            }
            set {
                this.profesorField = value;
                this.RaisePropertyChanged("profesor");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Services.upcnet.upc.com/")]
    public partial class curso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cicloDeCursoField;
        
        private string idCursoField;
        
        private string idProfesorField;
        
        private int maxInasistenciaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cicloDeCurso {
            get {
                return this.cicloDeCursoField;
            }
            set {
                this.cicloDeCursoField = value;
                this.RaisePropertyChanged("cicloDeCurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string idCurso {
            get {
                return this.idCursoField;
            }
            set {
                this.idCursoField = value;
                this.RaisePropertyChanged("idCurso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string idProfesor {
            get {
                return this.idProfesorField;
            }
            set {
                this.idProfesorField = value;
                this.RaisePropertyChanged("idProfesor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int maxInasistencia {
            get {
                return this.maxInasistenciaField;
            }
            set {
                this.maxInasistenciaField = value;
                this.RaisePropertyChanged("maxInasistencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoAlumnoByID", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoAlumnoByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public getCursoAlumnoByIDRequest() {
        }
        
        public getCursoAlumnoByIDRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoAlumnoByIDResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoAlumnoByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumno @return;
        
        public getCursoAlumnoByIDResponse() {
        }
        
        public getCursoAlumnoByIDResponse(UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumno @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoAlumnoByIdCurso", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoAlumnoByIdCursoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getCursoAlumnoByIdCursoRequest() {
        }
        
        public getCursoAlumnoByIdCursoRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoAlumnoByIdCursoResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoAlumnoByIdCursoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumno[] @return;
        
        public getCursoAlumnoByIdCursoResponse() {
        }
        
        public getCursoAlumnoByIdCursoResponse(UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumno[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoByIdAlumno", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoByIdAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getCursoByIdAlumnoRequest() {
        }
        
        public getCursoByIdAlumnoRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoByIdAlumnoResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoByIdAlumnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceCursoAlumno.curso[] @return;
        
        public getCursoByIdAlumnoResponse() {
        }
        
        public getCursoByIdAlumnoResponse(UPCNETSystemCliente.UPCNETServiceCursoAlumno.curso[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoAlumnoReporte", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoAlumnoReporteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string idAlumno;
        
        public getCursoAlumnoReporteRequest() {
        }
        
        public getCursoAlumnoReporteRequest(string idAlumno) {
            this.idAlumno = idAlumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoAlumnoReporteResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoAlumnoReporteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumnoReporte[] @return;
        
        public getCursoAlumnoReporteResponse() {
        }
        
        public getCursoAlumnoReporteResponse(UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumnoReporte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editCursoAlumno", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class editCursoAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumno arg0;
        
        public editCursoAlumnoRequest() {
        }
        
        public editCursoAlumnoRequest(UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumno arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="editCursoAlumnoResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class editCursoAlumnoResponse {
        
        public editCursoAlumnoResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoAlumno", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoAlumnoRequest {
        
        public getCursoAlumnoRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCursoAlumnoResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class getCursoAlumnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumno[] @return;
        
        public getCursoAlumnoResponse() {
        }
        
        public getCursoAlumnoResponse(UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumno[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setCursoAlumno", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class setCursoAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Services.upcnet.upc.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumno arg0;
        
        public setCursoAlumnoRequest() {
        }
        
        public setCursoAlumnoRequest(UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumno arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setCursoAlumnoResponse", WrapperNamespace="http://Services.upcnet.upc.com/", IsWrapped=true)]
    public partial class setCursoAlumnoResponse {
        
        public setCursoAlumnoResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UPCNETServiceCursoAlumnoChannel : UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UPCNETServiceCursoAlumnoClient : System.ServiceModel.ClientBase<UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno>, UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno {
        
        public UPCNETServiceCursoAlumnoClient() {
        }
        
        public UPCNETServiceCursoAlumnoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UPCNETServiceCursoAlumnoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPCNETServiceCursoAlumnoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UPCNETServiceCursoAlumnoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIDResponse UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.getCursoAlumnoByID(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIDRequest request) {
            return base.Channel.getCursoAlumnoByID(request);
        }
        
        public UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumno getCursoAlumnoByID(string arg0, string arg1) {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIDRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIDRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIDResponse retVal = ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).getCursoAlumnoByID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIDResponse> UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.getCursoAlumnoByIDAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIDRequest request) {
            return base.Channel.getCursoAlumnoByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIDResponse> getCursoAlumnoByIDAsync(string arg0, string arg1) {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIDRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIDRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).getCursoAlumnoByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdCursoResponse UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.getCursoAlumnoByIdCurso(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdCursoRequest request) {
            return base.Channel.getCursoAlumnoByIdCurso(request);
        }
        
        public UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumno[] getCursoAlumnoByIdCurso(string arg0) {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdCursoRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdCursoRequest();
            inValue.arg0 = arg0;
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdCursoResponse retVal = ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).getCursoAlumnoByIdCurso(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdCursoResponse> UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.getCursoAlumnoByIdCursoAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdCursoRequest request) {
            return base.Channel.getCursoAlumnoByIdCursoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdCursoResponse> getCursoAlumnoByIdCursoAsync(string arg0) {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdCursoRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoByIdCursoRequest();
            inValue.arg0 = arg0;
            return ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).getCursoAlumnoByIdCursoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoByIdAlumnoResponse UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.getCursoByIdAlumno(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoByIdAlumnoRequest request) {
            return base.Channel.getCursoByIdAlumno(request);
        }
        
        public UPCNETSystemCliente.UPCNETServiceCursoAlumno.curso[] getCursoByIdAlumno(string arg0) {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoByIdAlumnoRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoByIdAlumnoRequest();
            inValue.arg0 = arg0;
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoByIdAlumnoResponse retVal = ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).getCursoByIdAlumno(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoByIdAlumnoResponse> UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.getCursoByIdAlumnoAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoByIdAlumnoRequest request) {
            return base.Channel.getCursoByIdAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoByIdAlumnoResponse> getCursoByIdAlumnoAsync(string arg0) {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoByIdAlumnoRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoByIdAlumnoRequest();
            inValue.arg0 = arg0;
            return ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).getCursoByIdAlumnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoReporteResponse UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.getCursoAlumnoReporte(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoReporteRequest request) {
            return base.Channel.getCursoAlumnoReporte(request);
        }
        
        public UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumnoReporte[] getCursoAlumnoReporte(string idAlumno) {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoReporteRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoReporteRequest();
            inValue.idAlumno = idAlumno;
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoReporteResponse retVal = ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).getCursoAlumnoReporte(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoReporteResponse> UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.getCursoAlumnoReporteAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoReporteRequest request) {
            return base.Channel.getCursoAlumnoReporteAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoReporteResponse> getCursoAlumnoReporteAsync(string idAlumno) {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoReporteRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoReporteRequest();
            inValue.idAlumno = idAlumno;
            return ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).getCursoAlumnoReporteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.editCursoAlumnoResponse UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.editCursoAlumno(UPCNETSystemCliente.UPCNETServiceCursoAlumno.editCursoAlumnoRequest request) {
            return base.Channel.editCursoAlumno(request);
        }
        
        public void editCursoAlumno(UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumno arg0) {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.editCursoAlumnoRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.editCursoAlumnoRequest();
            inValue.arg0 = arg0;
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.editCursoAlumnoResponse retVal = ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).editCursoAlumno(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.editCursoAlumnoResponse> UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.editCursoAlumnoAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.editCursoAlumnoRequest request) {
            return base.Channel.editCursoAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.editCursoAlumnoResponse> editCursoAlumnoAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumno arg0) {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.editCursoAlumnoRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.editCursoAlumnoRequest();
            inValue.arg0 = arg0;
            return ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).editCursoAlumnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoResponse UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.getCursoAlumno(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoRequest request) {
            return base.Channel.getCursoAlumno(request);
        }
        
        public UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumno[] getCursoAlumno() {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoRequest();
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoResponse retVal = ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).getCursoAlumno(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoResponse> UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.getCursoAlumnoAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoRequest request) {
            return base.Channel.getCursoAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoResponse> getCursoAlumnoAsync() {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.getCursoAlumnoRequest();
            return ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).getCursoAlumnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoResponse UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.setCursoAlumno(UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoRequest request) {
            return base.Channel.setCursoAlumno(request);
        }
        
        public void setCursoAlumno(UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumno arg0) {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoRequest();
            inValue.arg0 = arg0;
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoResponse retVal = ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).setCursoAlumno(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoResponse> UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno.setCursoAlumnoAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoRequest request) {
            return base.Channel.setCursoAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoResponse> setCursoAlumnoAsync(UPCNETSystemCliente.UPCNETServiceCursoAlumno.cursoAlumno arg0) {
            UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoRequest inValue = new UPCNETSystemCliente.UPCNETServiceCursoAlumno.setCursoAlumnoRequest();
            inValue.arg0 = arg0;
            return ((UPCNETSystemCliente.UPCNETServiceCursoAlumno.UPCNETServiceCursoAlumno)(this)).setCursoAlumnoAsync(inValue);
        }
    }
}
